"""Generate the paper's numbers and tables from results/metrics.csv.

Every number in the paper is emitted here, so `paper/main.tex` contains no hand-typed
result and cannot drift from what this run computed. Inline values become LaTeX macros
in `paper/numbers.tex`; tables become standalone `paper/tab_*.tex` files that main.tex
\\input.

Run: uv run python -m src.paper_numbers
"""

from __future__ import annotations

import json
import sys

import numpy as np
import pandas as pd

from . import config as C
from .dataset import OFFICIAL_SPLIT

LAB = {
    "trivial": "Trivial marginal",
    "lgbm_summary": "LGBM window-summary",
    "lgbm_raw": "LGBM raw-window",
    "tsfm": "Chronos-2 + MLP (point)",
    "tsfm_q": "Chronos-2 + MLP (quantile)",
    "tsfm_abl_reg": "Chronos-2 [REG] pooling",
    "control_randproj": "Random projection",
    "control_randproj_q": "Random projection (quantile)",
    "control_chanscramble": "Channel scramble",
    "control_shufflabel": "Shuffled labels",
}
BIN_TEX = {"gt100": "$>$100", "50to100": "50--100", "20to50": "20--50", "lt20": "$<$20"}
# Letter-only macro-name fragments for the bins and look-backs (see Macros.add).
BIN_MACRO = {"gt100": "BinHealthy", "50to100": "BinMid", "20to50": "BinLow",
             "lt20": "BinCritical"}
LB_MACRO = {"L30": "Primary", "L80": "Secondary"}


def esc(s: str) -> str:
    return s.replace("_", r"\_").replace("%", r"\%")


def sci(x: float, sig: int = 1) -> str:
    """LaTeX scientific notation. `3.3e-06` reads as source code in a paper."""
    from math import floor, log10

    if x == 0:
        return "0"
    e = int(floor(log10(abs(x))))
    m = x / 10**e
    # Bare math content, no $ delimiters: these macros are used both inside display
    # math (where $ would terminate it) and in running text (wrapped in $...$ there).
    return f"{m:.{sig}f}\\times 10^{{{e}}}"


class Macros:
    """Collects \\newcommand definitions, refusing silent redefinition."""

    def __init__(self):
        self.d: dict[str, str] = {}

    def add(self, name: str, value) -> None:
        # TeX control sequences are letters only. A name containing a digit does not
        # fail at generation time -- it fails later, inside LaTeX, as a confusing
        # "Missing \\endcsname" -- so reject it here where the cause is obvious.
        if not name.isalpha():
            raise ValueError(
                f"macro name {name!r} is not letters-only; TeX cannot define it. "
                "Use a letter-only semantic name (BinHealthy, not gt100)."
            )
        if name in self.d:
            raise KeyError(f"macro {name} defined twice")
        if isinstance(value, float):
            value = f"{value:.2f}"
        self.d[name] = str(value)

    def render(self) -> str:
        head = ("% Auto-generated by src/paper_numbers.py from results/metrics.csv.\n"
                "% Do not edit by hand: regenerate instead.\n")
        body = "\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(self.d.items()))
        return head + body + "\n"


def g(df, **kw):
    m = pd.Series(True, index=df.index)
    for k, v in kw.items():
        m &= (df[k] == v)
    return df[m]


def one(df, **kw):
    s = g(df, **kw)
    if len(s) != 1:
        raise LookupError(f"expected exactly 1 row for {kw}, got {len(s)}")
    return s.iloc[0]


def main() -> int:
    df = pd.read_csv(C.RESULTS / "metrics.csv")
    ev = g(df, split="eval", lookback=C.LOOKBACK)
    m = Macros()

    p1 = json.loads((C.RESULTS / "phase1_evidence.json").read_text())
    p3 = json.loads((C.RESULTS / "phase3_report.json").read_text())
    c1 = json.loads((C.RESULTS / "c1_comparison.json").read_text())
    diag = json.loads((C.RESULTS / "diag_head_budget.json").read_text())
    seed = json.loads((C.RESULTS / "seed_study.json").read_text())
    ridge = json.loads((C.RESULTS / "ridge_probe.json").read_text())
    clus = json.loads((C.RESULTS / "conformal_cluster.json").read_text())
    eqv = json.loads((C.RESULTS / "equivariance.json").read_text())
    std = json.loads((C.RESULTS / "standard_protocol.json").read_text())

    # ---------------------------------------------------------------- setup facts
    m.add("nUnits", p1["train_file"]["n_units"])
    m.add("nRows", f"{p1['train_file']['n_rows']:,}")
    m.add("trajMin", p1["train_file"]["trajectory_length"]["min"])
    m.add("trajMax", p1["train_file"]["trajectory_length"]["max"])
    m.add("trajMedian", f"{p1['train_file']['trajectory_length']['median']:.0f}")
    m.add("nTrainUnits", p1["splits"]["sizes"]["train"])
    m.add("nCalibUnits", p1["splits"]["sizes"]["calib"])
    m.add("nEvalUnits", p1["splits"]["sizes"]["eval"])
    m.add("nEvalWindows", p1["windows"]["eval"]["n_windows"])
    m.add("nCalibWindows", p1["windows"]["calib"]["n_windows"])
    m.add("nTrainWindows", f"{p1['windows']['train']['n_windows']:,}")
    m.add("lookback", C.LOOKBACK)
    m.add("lookbackSecondary", C.LOOKBACK_SECONDARY)
    m.add("rulCap", C.RUL_CAP)
    m.add("truncPerUnit", C.TRUNCATIONS_PER_UNIT)
    m.add("nDropped", p1["preprocessing"]["n_dropped"])
    m.add("nKept", p1["preprocessing"]["n_kept"])
    m.add("droppedCols", esc(", ".join(p1["preprocessing"]["dropped_constant"])))
    m.add("discardPct", f"{100*p1['windows']['discard_accounting']['fraction_discarded']:.1f}")
    m.add("discardCycles", f"{p1['windows']['discard_accounting']['total_discarded_cycles']:,}")
    m.add("capMassPct", f"{100*p1['targets']['eval']['frac_at_or_above_cap']:.1f}")
    m.add("nBootstrap", f"{C.BOOTSTRAP_RESAMPLES:,}")

    # ---------------------------------------------------------------- backbone/head
    m.add("backboneParams", f"{p3['backbone']['n_params']:,}")
    m.add("backboneRev", p3["backbone"]["revision"][:12])
    m.add("dModel", p3["backbone"]["d_model"])
    m.add("nLayers", p3["backbone"]["num_layers"])
    m.add("patchSize", C.BACKBONE_PATCH_SIZE)
    m.add("headParams", f"{p3['head']['point']['total']:,}")
    m.add("headHidden", C.HEAD_HIDDEN)
    m.add("headDropout", C.HEAD_DROPOUT)
    m.add("headInputDim", f"{p3['embedding_dim']['head_input_dim']:,}")
    m.add("backboneHeadRatio", f"{p3['head']['backbone_to_head_ratio']:.0f}")
    m.add("nPatchesPrimary", p3["extraction"]["per_split"]["train"]["n_patches"])
    m.add("nTokensPrimary", p3["extraction"]["per_split"]["train"]["n_tokens"])
    m.add("extractSeconds", f"{p3['extraction']['measured_wall_seconds']:.0f}")
    m.add("nExtractWindows", f"{p3['extraction']['n_windows']:,}")
    m.add("msPerWindow", f"{p3['extraction']['per_split']['train']['ms_per_window']:.1f}")

    # ---------------------------------------------------------------- C1
    for arm in LAB:
        for v in ("A", "B"):
            try:
                r = one(ev, arm=arm, variant=v, metric="rmse", rul_bin="all",
                        conformal="point")
            except LookupError:
                continue
            key = arm.replace("_", "") + v
            m.add(f"rmse{key}", r["value"])
            m.add(f"rmse{key}Lo", r["ci_lo"])
            m.add(f"rmse{key}Hi", r["ci_hi"])
            mae = one(ev, arm=arm, variant=v, metric="mae", rul_bin="all",
                      conformal="point")
            m.add(f"mae{key}", mae["value"])

    for v in ("A", "B"):
        d = c1["primary_paired"][f"tsfm_minus_lgbm_summary__{v}"]
        m.add(f"dTsfmLgbm{v}", f"{d['point']:+.2f}")
        m.add(f"dTsfmLgbm{v}Lo", f"{d['ci_lo']:+.2f}")
        m.add(f"dTsfmLgbm{v}Hi", f"{d['ci_hi']:+.2f}")
        d2 = c1["secondary_paired"][f"tsfm_minus_lgbm_summary__{v}"]
        m.add(f"dTsfmLgbmSecondary{v}", f"{d2['point']:+.2f}")
        m.add(f"dTsfmLgbmSecondary{v}Lo", f"{d2['ci_lo']:+.2f}")
        m.add(f"dTsfmLgbmSecondary{v}Hi", f"{d2['ci_hi']:+.2f}")
        dc = c1["controls_vs_tsfm"][f"control_randproj__{v}"]["diff_vs_tsfm"]
        m.add(f"dRandprojTsfm{v}", f"{dc['point']:+.2f}")
        m.add(f"dRandprojTsfm{v}Lo", f"{dc['ci_lo']:+.2f}")
        m.add(f"dRandprojTsfm{v}Hi", f"{dc['ci_hi']:+.2f}")
        for arm in ("tsfm", "lgbm_summary", "control_randproj"):
            key = arm.replace("_", "") + v
            m.add(f"ratio{key}Primary",
                  f"{c1['primary'][f'{arm}__{v}']['rmse_over_trivial']:.3f}")
            m.add(f"ratio{key}Secondary",
                  f"{c1['secondary'][f'{arm}__{v}']['rmse_over_trivial']:.3f}")
    dq = c1["controls_vs_tsfm"]["control_randproj_q__A"]["diff_vs_tsfm"]
    m.add("dRandprojqTsfmA", f"{dq['point']:+.2f}")
    m.add("dRandprojqTsfmALo", f"{dq['ci_lo']:+.2f}")
    m.add("dRandprojqTsfmAHi", f"{dq['ci_hi']:+.2f}")

    # ---------------------------------------------------------------- C2 / C3
    for arm in ("trivial", "lgbm_summary", "lgbm_raw", "tsfm_q", "control_randproj_q"):
        for v in ("A", "B"):
            r = one(ev, arm=arm, variant=v, metric="coverage", rul_bin="all",
                    conformal="marginal", nominal=0.90)
            w = one(ev, arm=arm, variant=v, metric="width_mean", rul_bin="all",
                    conformal="marginal", nominal=0.90)
            key = arm.replace("_", "") + v
            m.add(f"marg{key}", f"{100*r['value']:.1f}")
            m.add(f"marg{key}Lo", f"{100*r['ci_lo']:.1f}")
            m.add(f"marg{key}Hi", f"{100*r['ci_hi']:.1f}")
            m.add(f"margw{key}", f"{w['value']:.0f}")
    for arm in LAB:
        for v in ("A", "B"):
            try:
                r = one(ev, arm=arm, variant=v, metric="coverage", rul_bin="all",
                        conformal="conformal", nominal=0.90)
                w = one(ev, arm=arm, variant=v, metric="width_mean", rul_bin="all",
                        conformal="conformal", nominal=0.90)
            except LookupError:
                continue
            key = arm.replace("_", "") + v
            m.add(f"conf{key}", f"{100*r['value']:.1f}")
            m.add(f"conf{key}Lo", f"{100*r['ci_lo']:.1f}")
            m.add(f"conf{key}Hi", f"{100*r['ci_hi']:.1f}")
            m.add(f"confw{key}", f"{w['value']:.0f}")
    for v in ("A", "B"):
        mw = float(one(ev, arm="tsfm_q", variant=v, metric="width_mean",
                       rul_bin="all", conformal="marginal", nominal=0.90)["value"])
        cw = float(one(ev, arm="tsfm_q", variant=v, metric="width_mean",
                       rul_bin="all", conformal="conformal", nominal=0.90)["value"])
        m.add(f"inflTsfmq{v}", f"{cw/mw:.2f}")
        mw2 = float(one(ev, arm="lgbm_summary", variant=v, metric="width_mean",
                        rul_bin="all", conformal="marginal", nominal=0.90)["value"])
        cw2 = float(one(ev, arm="lgbm_summary", variant=v, metric="width_mean",
                        rul_bin="all", conformal="conformal", nominal=0.90)["value"])
        m.add(f"inflLgbm{v}", f"{cw2/mw2:.2f}")

    # Conformal-vs-nominal aggregate honesty statistics.
    cc = g(df, split="eval", lookback=C.LOOKBACK, conformal="conformal",
           metric="coverage", rul_bin="all")
    inside = int(((cc.ci_lo <= cc.nominal) & (cc.ci_hi >= cc.nominal)).sum())
    below = int((cc.ci_hi < cc.nominal).sum())
    m.add("confCellsTotal", len(cc))
    m.add("confCellsInside", inside)
    m.add("confCellsBelow", below)
    m.add("confMaxAbsDev",
          f"{float((cc.groupby('nominal').value.mean() - cc.nominal.unique()).abs().max()*100):.1f}")

    # Regime conditioning at nominal 90%.
    for arm in ("tsfm_q", "lgbm_summary", "tsfm", "trivial"):
        for v in ("A", "B"):
            for tag in ("marginal", "conformal"):
                for b in BIN_TEX:
                    try:
                        r = one(ev, arm=arm, variant=v, metric="coverage", rul_bin=b,
                                conformal=tag, nominal=0.90)
                    except LookupError:
                        continue
                    key = arm.replace("_", "") + v + tag[:4].capitalize() + BIN_MACRO[b]
                    m.add(f"reg{key}", f"{100*r['value']:.1f}")

    # Pinball.
    for arm in ("tsfm_q", "lgbm_summary", "lgbm_raw", "control_randproj_q", "trivial"):
        for v in ("A", "B"):
            r = one(ev, arm=arm, variant=v, metric="pinball_mean", rul_bin="all",
                    conformal="marginal")
            m.add(f"pin{arm.replace('_','')}{v}", f"{r['value']:.2f}")

    # Official test set.
    off = g(df, split=OFFICIAL_SPLIT, lookback=C.LOOKBACK, metric="rmse",
            rul_bin="all", conformal="point")
    m.add("nOfficialUnits", int(off.n_windows.iloc[0]))
    for arm in LAB:
        for v in ("A", "B"):
            s = g(off, arm=arm, variant=v)
            if len(s) == 1:
                m.add(f"off{arm.replace('_','')}{v}", s.iloc[0]["value"])

    # Head-budget diagnostic.
    m.add("diagRefRmse", diag["reference_lgbm_summary_A_rmse"])
    best = min(diag["grid"], key=lambda r: r["eval_rmse"])
    m.add("diagBestRmse", best["eval_rmse"])
    m.add("diagBestDelta", f"{best['delta_vs_ref']:+.2f}")
    m.add("diagBestM", best["m"])
    m.add("diagBestEpochs", best["epochs"])
    base = [r for r in diag["grid"] if r["m"] == 32 and r["epochs"] == 50][0]
    m.add("diagLossDrop", f"{base['final_loss']/best['final_loss']:.1f}")

    # ------------------------------------------ M6: standard-protocol comparability
    sb = std["B"]
    m.add("stdRmse", f"{sb['rmse']:.2f}")
    m.add("stdRmseLo", f"{sb['rmse_ci_lo']:.2f}")
    m.add("stdRmseHi", f"{sb['rmse_ci_hi']:.2f}")
    m.add("stdMae", f"{sb['mae']:.2f}")
    m.add("stdEngines", sb["n_test_engines"])
    m.add("stdTrainWindows", f"{sb['n_train_windows']:,}")

    # ------------------------------------------- lead result: equivariance
    m.add("eqvEqui", sci(eqv["equivariance_max_abs_diff"]))
    m.add("eqvInv", sci(eqv["variate_mean_invariance_max_abs_diff"]))
    m.add("eqvScale", f"{eqv['effect_scale_max_abs_diff']:.2f}")
    m.add("eqvRatio", f"{eqv['scale_over_equivariance_ratio']:,.0f}")
    m.add("eqvNWindows", eqv["n_windows"])
    m.add("eqvNVariates", eqv["n_variates"])

    # ------------------------------------------------------- M1: seed replication
    m.add("nSeeds", seed["n_seeds"])
    for key, v in seed["arms"].items():
        arm, variant = key.split("__")
        k = arm.replace("_", "") + variant
        m.add(f"seedmean{k}", f"{v['mean']:.2f}")
        m.add(f"seedsd{k}", f"{v['sd']:.2f}")
        m.add(f"seedspread{k}", f"{v['spread']:.2f}")
        m.add(f"seedzero{k}", f"{100*v['zero_pred_fraction_mean']:.1f}")
    m.add("seedsdMax", f"{max(v['sd'] for v in seed['arms'].values()):.2f}")
    m.add("seedspreadMax", f"{max(v['spread'] for v in seed['arms'].values()):.2f}")
    for key, v in seed["combined_paired"].items():
        base, variant = key.rsplit("__", 1)
        k = base.replace("_minus_", "Minus").replace("_", "") + variant
        m.add(f"comb{k}", f"{v['point_mean_over_seeds']:+.2f}")
        m.add(f"comb{k}Lo", f"{v['ci_lo']:+.2f}")
        m.add(f"comb{k}Hi", f"{v['ci_hi']:+.2f}")
    for key, v in seed["m2"].items():
        src, variant = key.split("__")
        m.add(f"mtwoGain{src}{variant}", f"{v['gain']:+.2f}")

    # ---------------------------------------------------------- M4: ridge probe
    for key, v in ridge["probes"].items():
        name, variant = key.split("__")
        k = name + variant
        m.add(f"ridge{k}", f"{v['rmse']:.2f}")
        m.add(f"ridge{k}Lo", f"{v['rmse_ci_lo']:.2f}")
        m.add(f"ridge{k}Hi", f"{v['rmse_ci_hi']:.2f}")
        m.add(f"ridgealpha{k}", f"{v['alpha']:.3g}")
        m.add(f"ridgedim{k}", f"{v['dim']:,}")
    for key, v in ridge["paired"].items():
        base, variant = key.rsplit("__", 1)
        k = base.replace("_minus_", "Minus").replace("_", "") + variant
        m.add(f"rp{k}", f"{v['point']:+.2f}")
        m.add(f"rp{k}Lo", f"{v['ci_lo']:+.2f}")
        m.add(f"rp{k}Hi", f"{v['ci_hi']:+.2f}")
    m.add("ridgeValUnits", ridge["n_val_units"])
    m.add("ridgeNAlphas", len(ridge["alphas"]))

    # -------------------------------------------------------- M3: ratios with CIs
    for key, v in c1["ratios"].items():
        arm, variant, lb = key.split("__")
        k = arm.replace("_", "") + variant + ("Primary" if lb == f"L{C.LOOKBACK}"
                                              else "Secondary")
        m.add(f"rat{k}", f"{v['point']:.3f}")
        m.add(f"rat{k}Lo", f"{v['ci_lo']:.3f}")
        m.add(f"rat{k}Hi", f"{v['ci_hi']:.3f}")

    # ------------------------------------------------------ M7: cluster conformal
    for key, v in clus["cells"].items():
        arm, variant = key.rsplit("__", 1)
        k = arm.replace("_", "") + variant
        m.add(f"clfull{k}", f"{100*v['full_coverage']:.1f}")
        if v["cluster_coverage_mean"] is not None:
            m.add(f"clsub{k}", f"{100*v['cluster_coverage_mean']:.1f}")
            m.add(f"clsubsd{k}", f"{100*v['cluster_coverage_sd']:.1f}")
            m.add(f"clsubw{k}", f"{v['cluster_width_mean']:.0f}")
    m.add("clNDraws", clus["n_draws"])
    m.add("clMethodTsfm", clus["cells"]["tsfm__A"]["method"])
    m.add("clMethodTsfmq", clus["cells"]["tsfm_q__A"]["method"])

    (C.PAPER / "numbers.tex").write_text(m.render())
    print(f"  wrote paper/numbers.tex ({len(m.d)} macros)")

    _tab_main(ev, seed, ridge)
    _tab_ratio(c1)
    _tab_seed(seed)
    _tab_c1(ev, df, C1_BODY, "tab_c1.tex")
    _tab_c1(ev, df, C1_FULL, "tab_c1_full.tex")
    _tab_calibration(ev, ["trivial", "lgbm_summary", "tsfm_q", "control_randproj_q"],
                     "tab_calibration.tex")
    _tab_calibration(ev, ["trivial", "lgbm_summary", "lgbm_raw", "tsfm", "tsfm_q",
                          "control_randproj_q"], "tab_calibration_full.tex")
    _tab_regime(ev)
    return 0


C1_BODY = ["trivial", "lgbm_summary", "lgbm_raw", "tsfm", "tsfm_q",
           "control_randproj", "control_randproj_q"]
C1_FULL = ["trivial", "lgbm_summary", "lgbm_raw", "tsfm", "tsfm_q", "tsfm_abl_reg",
           "control_randproj", "control_randproj_q", "control_chanscramble",
           "control_shufflabel"]


def _tab_c1(ev, df, order=None, out="tab_c1.tex") -> None:
    """Point accuracy at the primary look-back."""
    order = order or C1_BODY
    lines = [
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"& & \multicolumn{2}{c}{Variant A (uncapped)} & \multicolumn{2}{c}{Variant B (cap \rulCap)} \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
        r"Arm & Group & RMSE [95\% CI] & MAE & RMSE [95\% CI] & MAE \\",
        r"\midrule",
    ]
    groups = {"trivial": "base", "lgbm_summary": "base", "lgbm_raw": "base",
              "tsfm": "TSFM", "tsfm_q": "TSFM", "tsfm_abl_reg": "TSFM"}
    for arm in order:
        cells = []
        for v in ("A", "B"):
            try:
                r = one(ev, arm=arm, variant=v, metric="rmse", rul_bin="all",
                        conformal="point")
                mae = one(ev, arm=arm, variant=v, metric="mae", rul_bin="all",
                          conformal="point")
            except LookupError:
                cells += ["--", "--"]
                continue
            cells.append(f"{r['value']:.2f} [{r['ci_lo']:.1f}, {r['ci_hi']:.1f}]")
            cells.append(f"{mae['value']:.2f}")
        grp = groups.get(arm, "control")
        lines.append(f"{LAB[arm]} & {grp} & " + " & ".join(cells) + r" \\")
        if arm in ("lgbm_raw", "tsfm_abl_reg") or (
                arm == "tsfm_q" and "tsfm_abl_reg" not in order):
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (C.PAPER / out).write_text("\n".join(lines) + "\n")
    print(f"  wrote paper/{out}")


def _tab_calibration(ev, arms=None, out="tab_calibration.tex") -> None:
    """Coverage and width, marginal vs conformal, at all five nominal levels.

    Coverage and width share a cell as "cov (width)" rather than occupying two rows
    each: it halves the table height without dropping the width, which must never be
    separated from its coverage number.
    """
    arms = arms or ["trivial", "lgbm_summary", "lgbm_raw", "tsfm", "tsfm_q",
                    "control_randproj_q"]
    lines = [
        r"\begin{tabular}{ll" + "r" * len(C.NOMINAL_LEVELS) + r"}",
        r"\toprule",
        r"Arm & Intervals & " +
        " & ".join(f"{lv:.0%}".replace("%", r"\%") for lv in C.NOMINAL_LEVELS) + r" \\",
        r"\midrule",
    ]
    for arm in arms:
        for tag in ("marginal", "conformal"):
            cells = []
            for lv in C.NOMINAL_LEVELS:
                try:
                    r = one(ev, arm=arm, variant="A", metric="coverage",
                            rul_bin="all", conformal=tag, nominal=lv)
                    w = one(ev, arm=arm, variant="A", metric="width_mean",
                            rul_bin="all", conformal=tag, nominal=lv)
                    cells.append(f"{100*r['value']:.1f} ({w['value']:.0f})")
                except LookupError:
                    cells.append("--")
            lines.append(f"{LAB[arm]} & {tag} & " + " & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    (C.PAPER / out).write_text("\n".join(lines) + "\n")
    print(f"  wrote paper/{out}")


def _tab_regime(ev) -> None:
    """Regime-conditioned coverage at nominal 90%."""
    arms = ["trivial", "lgbm_summary", "lgbm_raw", "tsfm", "tsfm_q",
            "control_randproj_q"]
    bins = list(BIN_TEX)
    lines = [
        r"\begin{tabular}{ll" + "r" * len(bins) * 2 + r"}",
        r"\toprule",
        r"& & \multicolumn{4}{c}{Own intervals} & \multicolumn{4}{c}{After conformal} \\",
        r"\cmidrule(lr){3-6}\cmidrule(lr){7-10}",
        r"Arm & V & " + " & ".join(BIN_TEX[b] for b in bins) + " & "
        + " & ".join(BIN_TEX[b] for b in bins) + r" \\",
        r"\midrule",
    ]
    for arm in arms:
        for v in ("A", "B"):
            cells = []
            for tag in ("marginal", "conformal"):
                for b in bins:
                    try:
                        r = one(ev, arm=arm, variant=v, metric="coverage", rul_bin=b,
                                conformal=tag, nominal=0.90)
                        cells.append(f"{100*r['value']:.0f}")
                    except LookupError:
                        cells.append("--")
            lines.append(f"{LAB[arm]} & {v} & " + " & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    (C.PAPER / "tab_regime.tex").write_text("\n".join(lines) + "\n")
    print("  wrote paper/tab_regime.tex")




# ---------------------------------------------------------------- new tables

MAIN_ROWS = [
    ("trivial", "Trivial marginal", None, None),
    ("lgbm_summary", "LGBM window-summary", None, "summary"),
    ("lgbm_raw", "LGBM raw-window", None, "raw"),
    ("tsfm", "Chronos-2 (MSE head)", "tsfm", "chronos"),
    ("tsfm_q", "Chronos-2 (pinball head)", "tsfm_q", None),
    ("control_randproj", "Random projection (MSE)", "control_randproj", "randproj"),
    ("control_randproj_q", "Random projection (pinball)", "control_randproj_q", None),
]


def _tab_main(ev, seed, ridge) -> None:
    """One table answering M1 and M4: seed-aware heads beside head-free ridge probes."""
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Variant A (uncapped)} & \multicolumn{2}{c}{Variant B (cap \rulCap)} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"Arm / representation & specified head & ridge probe & specified head & ridge probe \\",
        r"\midrule",
    ]
    for arm, label, seed_key, ridge_key in MAIN_ROWS:
        cells = []
        for v in ("A", "B"):
            if seed_key and f"{seed_key}__{v}" in seed["arms"]:
                a = seed["arms"][f"{seed_key}__{v}"]
                cells.append(f"{a['mean']:.2f} $\\pm$ {a['sd']:.2f}")
            else:
                r = one(ev, arm=arm, variant=v, metric="rmse", rul_bin="all",
                        conformal="point")
                cells.append(f"{r['value']:.2f}")
            if ridge_key and f"{ridge_key}__{v}" in ridge["probes"]:
                cells.append(f"{ridge['probes'][f'{ridge_key}__{v}']['rmse']:.2f}")
            else:
                cells.append("--")
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (C.PAPER / "tab_main.tex").write_text("\n".join(lines) + "\n")
    print("  wrote paper/tab_main.tex")


def _tab_ratio(c1) -> None:
    """M3: the only cross-look-back comparable quantity, with intervals."""
    arms = ["lgbm_summary", "lgbm_raw", "tsfm", "control_randproj"]
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Variant A} & \multicolumn{2}{c}{Variant B} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"Arm & $L{=}\lookback$ & $L{=}\lookbackSecondary$ & $L{=}\lookback$ & $L{=}\lookbackSecondary$ \\",
        r"\midrule",
    ]
    for arm in arms:
        cells = []
        for v in ("A", "B"):
            for L in (C.LOOKBACK, C.LOOKBACK_SECONDARY):
                d = c1["ratios"].get(f"{arm}__{v}__L{L}")
                cells.append("--" if d is None else
                             "%.3f [%.3f, %.3f]" % (d["point"], d["ci_lo"], d["ci_hi"]))
        lines.append(f"{LAB[arm]} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (C.PAPER / "tab_ratio.tex").write_text("\n".join(lines) + "\n")
    print("  wrote paper/tab_ratio.tex")


def _tab_seed(seed) -> None:
    """Appendix: full seed distribution and the dead-output diagnostic."""
    lines = [
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Arm & V & mean & sd & min & max & preds $=0$ \\",
        r"\midrule",
    ]
    for key in sorted(seed["arms"]):
        arm, v = key.split("__")
        a = seed["arms"][key]
        lines.append(f"{LAB.get(arm, arm)} & {v} & {a['mean']:.2f} & {a['sd']:.2f} & "
                     f"{a['min']:.2f} & {a['max']:.2f} & "
                     f"{100*a['zero_pred_fraction_mean']:.1f}\\% \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (C.PAPER / "tab_seed.tex").write_text("\n".join(lines) + "\n")
    print("  wrote paper/tab_seed.tex")


if __name__ == "__main__":
    sys.exit(main())
